### ISSUE TITLE
Would anyone like to become a maintainer with me?

### ISSUE THREAD

**Issue by tjex** [jdan/cleaver#181]
Started using cleaver and really liking it. A really well rounded solution for markdown presentations. 
Others have too much complexity / features. Others are too stripped back. Others are broken...

But last activity here was 2017... It would be a shame for this project to fizzle out considering there's been so many contributions and is still a nicely functioning program despite having not been updated in 6 years!

Are there any contributors hanging around who would like to become maintainers with me?
I definitely need help as I'm not confident enough to not totally break the project if left up to my own devices...

@jdan . Thoughts?

**Comment by jdan** [comment]
@tjex My rule of thumb is if you send me a PR I'll add you as a collaborator! Maintainers come and go, but I'm always pleasantly impressed with what happens when you give people ownership.

**Comment by tjex** [comment]
Alright, great!
Have you considered upgrading the whole project to ES6? 
Is that something that would be good to have done?

And/or are there any other major todo's?

**Comment by jdan** [comment]
Peaceful with any and all upgrades! We could use some tests too to make
sure these upgrades don’t change any behavior :)

On October 11, 2023, Mads Hougesen ***@***.***> wrote:
> Alright, great!
>  Have you considered upgrading the whole project to ES6?
>  Is that something that would be good to have done?
>
> And/or are there any other major todo's?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/jdan/cleaver/issues/181#issuecomment-1757133327>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/AACGEJEPXDHMIZQAHIJZEPTX6ZKZ5ANCNFSM6AAAAAA52XWNOQ>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by tjex** [comment]
rad. well. I'll have a crack and keep you posted. Heads up though, progress will be fairly slow going.
I'm writing my masters thesis at the moment. And I'm far from a seasoned programmer...
